"use client";

import type { NextPage } from "next";
import { useEffect, useState } from "react";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import refreshAccessToken from "@/actions/refreshAccessToken";
import getAccessToken from "@/actions/getAccessToken";

const Home: NextPage = () => {
  const session = useSession();
  const [data, setData] = useState(null);

  console.log("session is ", session);
  useEffect(() => {
    async function getData(accessToken? : string | undefined) {
      if (!accessToken) accessToken = await getAccessToken();
      // console.log("acesstoken is ", accessToken);
      const response = await fetch(
        `https://api.spotify.com/v1/users/${"smedjan"}/playlists`,
        {
          headers: {
            Authorization: "Bearer " + accessToken,
          },
        },
      );
      if (!response.ok) {
        console.log(
          "something went wrong. assuming access token is bad. refrehsing it now. res is ",
          response.text(),
        );
        const newAccessToken = await refreshAccessToken();
        if (newAccessToken) {
          await getData(newAccessToken);
        }
      } else {
        const data = await response.json();
        console.log("data is ", data);
        setData(data);
      }
    }
    getData();
  }, []);

  // const params = new URLSearchParams();
  // params.append('scope', "user-read-private user-read-email");
  // console.log(params.toString())

  return (
    <div className={styles.container}>
      <Head>
        <title>NextAuth.js Spotify example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome,{" "}
          {session.status === "authenticated"
            ? session.data.user?.name || "friend"
            : "stranger"}
          !
        </h1>
        <p>
          {session.status === "authenticated" ? (
            <button
              className={styles.button}
              type="button"
              onClick={() => signOut()}
            >
              Sign out {session.data.user?.email}
            </button>
          ) : (
            <button
              className={styles.button}
              type="button"
              onClick={() => signIn("spotify")}
              disabled={session.status === "loading"}
            >
              Sign in with Spotify
            </button>
          )}
        </p>
        <p>
          <a href="https://github.com/davidjones418/next-auth-spotify-example#readme">
            What is this?
          </a>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
