import type { Metadata } from "next";
import "@/app/globals.css";
import Provider from "@/components/Provider";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className="dark font-primary flex flex-col h-screen justify-between items-center">
          <div className="bg-inherit w-full">
            <NavBar />
            {children}
          </div>
          {/* <Toaster />
            <Footer /> */}
        </body>
      </Provider>
    </html>
  );
}
